### ISSUE TITLE
Fix Layout

### ISSUE THREAD

**Issue by anhtp1608** [WolfCanCode/website-checker-system#6]
<img width="1659" alt="screen shot 2018-10-08 at 15 08 33" src="https://user-images.githubusercontent.com/27717331/46597915-528fc500-cb0c-11e8-8f25-cf87c13b9eca.png">

Fix nav menu

**Comment by WolfCanCode** [comment]
Ủa đáng phải fix cái table chứ. Cái table phải pagin hay scroll ấy phúc anh ơi

**Comment by anhtp1608** [comment]
ohm rồi ok, sợ bị vỡ layout thôi

**Comment by WolfCanCode** [comment]
@anhtp1608 oke vậy đóng nha
