### ISSUE TITLE
Replace all template data on UI

### ISSUE THREAD

**Issue by vinguyen1996** [WolfCanCode/website-checker-system#8]
Xóa hết tất cả data giả nào đang có chữ block.vn, hình của block.vn (Favicon test).
Chia task kiểm tra + xóa  theo phân công thiết kế UI bữa trước luôn nha.

**Comment by vinguyen1996** [comment]
![block](https://user-images.githubusercontent.com/43748297/46605970-79a6c080-cb25-11e8-9aa4-5c2b36e91816.PNG)
![block2](https://user-images.githubusercontent.com/43748297/46605971-79a6c080-cb25-11e8-8890-d964ed32c04a.PNG)
![block3](https://user-images.githubusercontent.com/43748297/46605972-7a3f5700-cb25-11e8-8a50-8273e1d87b83.PNG)
![block4](https://user-images.githubusercontent.com/43748297/46605973-7a3f5700-cb25-11e8-8a58-0d0dad68b181.PNG)
![block5](https://user-images.githubusercontent.com/43748297/46605975-7a3f5700-cb25-11e8-850d-7c092dcbe58c.PNG)

**Comment by WolfCanCode** [comment]
Để T xoá cho Vi

**Comment by WolfCanCode** [comment]
Xong rồi nha Vi :))))
